In [11]:
import pandas as pd
from utilities.sectoral_diff_report import SectoralDiffReport
import os

In [12]:
WORKING_DIR = os.getcwd()
SIM_FILES_DIR_PATH = os.path.join(WORKING_DIR, 'simulation_files')
MISC_DIR_PATH = os.path.join(WORKING_DIR, 'misc')

In [ ]:
iso_alpha_3 = 'HRV' # Set this to your desired country code

In [13]:
model_output_df = pd.read_csv(os.path.join(SIM_FILES_DIR_PATH, 'MODEL_OUTPUT.csv'))
model_output_df.head()

   primary_id  ... yield_agrc_vegetables_and_vines_tonne
0           0  ...                          3.579152e+06
1           0  ...                          3.528621e+06
2           0  ...                          3.678028e+06
3           0  ...                          3.584608e+06
4           0  ...                          3.602538e+06

[5 rows x 1453 columns]

In [ ]:
sdr = SectoralDiffReport(MISC_DIR_PATH, iso_alpha_3, init_year=2015)

In [15]:
detailed_report,  subsector_report = sdr.generate_diff_reports(model_output_df)

All variables from Vars are present in simulation_df.

/home/tony/ssp/croatia_data_calibration/utilities/sectoral_diff_report.py:112: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0.9949669191647061' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  detailed_report_draft_df.at[index, 'Simulation_Values'] = subsector_total_emissions

In [17]:
detailed_report.head()

   Year Subsector  ... Edgar_Values         diff
0  2015      agrc  ...     0.000227  2208.649075
1  2015      agrc  ...     0.095857     4.870426
2  2015      agrc  ...     1.038055     0.101643
3  2015      entc  ...     0.004396    68.266709
4  2015      entc  ...     3.297328    -0.122378

[5 rows x 6 columns]

In [18]:
subsector_report.head()

   Year Subsector  Simulation_Values  Edgar_Values      diff
0  2015      agrc           2.207085      1.134139  0.946045
1  2015      entc           3.229252      3.312946 -0.025263
2  2015      fgtv           0.209200      2.441121 -0.914302
3  2015      frst           2.053057     -6.547104 -1.313582
4  2015      inen           2.600468      2.157340  0.205405